# Generated by Django 4.1.7 on 2023-05-03 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customusermanager_alter_customuser_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserManager',
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscriptions',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subscribers',
            field=models.ManyToManyField(related_name='Fans', to=settings.AUTH_USER_MODEL),
        ),
    ]
