# Generated by Django 4.1.7 on 2023-08-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_customusermanager_customuser_subscriptions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='reputation',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='avatar/user.png', upload_to='media/avatar', verbose_name='Аватарка'),
        ),
    ]
