# Generated by Django 4.1.7 on 2023-09-10 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_commentcommunitymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentcommunitymodel',
            name='avtor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentcommunitymodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='usermassage/<django.db.models.fields.related.ForeignKey>/2023-09-10 22:26:00.790712'),
        ),
    ]
