# Generated by Django 4.1.7 on 2023-08-27 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import video.rename_file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReatingUserRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_viewed', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_reating', models.DateTimeField(blank=True)),
                ('is_like', models.BooleanField(blank=True)),
                ('is_dislike', models.BooleanField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_set_reating', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('genre', models.CharField(choices=[('Game', 'Game'), ('Travel', 'Travel'), ('News', 'News'), ('Music', 'Music'), ('Trailer', 'Trailer')], max_length=100)),
                ('date_public', models.DateTimeField(default=django.utils.timezone.now)),
                ('video', models.FileField(upload_to=video.rename_file.RenameFile())),
                ('title_image', models.ImageField(upload_to=video.rename_file.RenameFile(), verbose_name='Title image')),
                ('avtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reating', models.ManyToManyField(related_name='likes', through='video.ReatingUserRelation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WatchLaterRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.videomodel')),
            ],
        ),
        migrations.AddField(
            model_name='videomodel',
            name='watch_later',
            field=models.ManyToManyField(related_name='watch_later_rel', through='video.WatchLaterRelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Trends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.FloatField()),
                ('video', models.ManyToManyField(to='video.videomodel')),
            ],
        ),
        migrations.AddField(
            model_name='reatinguserrelation',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_reating', to='video.videomodel'),
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_image', models.ImageField(null=True, upload_to='playlists/', verbose_name='Title image')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[(1, 'Open'), (2, 'On link'), (3, 'Close')], max_length=20)),
                ('avtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_saved', models.ManyToManyField(blank=True, related_name='saved', to=settings.AUTH_USER_MODEL)),
                ('video', models.ManyToManyField(blank=True, to='video.videomodel')),
            ],
        ),
        migrations.CreateModel(
            name='MusicCharts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.FloatField()),
                ('video', models.ManyToManyField(to='video.videomodel')),
            ],
        ),
        migrations.CreateModel(
            name='Hashtags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=150)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.videomodel')),
            ],
        ),
        migrations.CreateModel(
            name='GameTop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.FloatField()),
                ('video', models.ManyToManyField(to='video.videomodel')),
            ],
        ),
        migrations.CreateModel(
            name='CommentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_public', models.DateTimeField(default=django.utils.timezone.now)),
                ('avtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.videomodel')),
            ],
        ),
    ]
