# Generated by Django 4.1.7 on 2023-08-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reatinguserrelation',
            name='date_reating',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
