# Generated by Django 4.1.7 on 2023-08-28 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0003_rename_reatinguserrelation_reatingvideorelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='avtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avtor_video', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserViewRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_viewed', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_viewd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.videomodel')),
            ],
        ),
        migrations.AddField(
            model_name='videomodel',
            name='user_views',
            field=models.ManyToManyField(blank=True, related_name='views_history', through='video.UserViewRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
