# Generated by Django 4.1.7 on 2023-08-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_alter_videomodel_avtor_userviewrelation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomodel',
            name='user_views',
        ),
        migrations.AlterField(
            model_name='reatingvideorelation',
            name='is_dislike',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='reatingvideorelation',
            name='is_like',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.DeleteModel(
            name='UserViewRelation',
        ),
    ]
