# Generated by Django 4.1.7 on 2023-08-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_remove_videomodel_user_views_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reatingvideorelation',
            name='date_viewed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
