# Generated by Django 4.1.7 on 2023-08-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_alter_reatingvideorelation_date_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reatingvideorelation',
            name='date_viewed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
