# Generated by Django 4.1.7 on 2023-09-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_alter_reatingvideorelation_date_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('On link', 'On link'), ('Close', 'Close')], max_length=20),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='title_image',
            field=models.ImageField(blank=True, upload_to='playlists/', verbose_name='Title image'),
        ),
    ]
